version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "First Job Running"
      - run: ls -l
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run: echo "Sleeping for 25 seconds"
      - run: sleep 25
      - run: echo "Napping time over - checking the new directory structure"
      - run: ls -l
      - persist_to_workspace:
        root: my_workspace
        paths:
          - echo_output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Running Second Job"
      - attach_workspace:
        at: my_workspace
      - run: ls -l
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
        requires:
          - one
